import ExcelJS from 'exceljs';

interface IncidentExportData {
  incidents: {
    id: number;
    incidentRef: string;
    incidentDate: Date | null;
    incidentTime: string | null;
    location: string | null;
    severity: string | null;
    status: string | null;
    personType: string | null;
    personName: string | null;
    staffInvolved: string | null;
    description: string | null;
    immediateActions: string | null;
    witnesses: string | null;
    notifiedCqc: boolean | null;
    notifiedCouncil: boolean | null;
    notifiedPolice: boolean | null;
    notifiedFamily: boolean | null;
    notifiedIco: boolean | null;
    investigationRequired: boolean | null;
    investigationNotes: string | null;
    actionsRequired: string | null;
    lessonsLearned: string | null;
    reportedBy: string | null;
    createdAt: Date | null;
    updatedAt: Date | null;
  }[];
  companyName: string;
  locationName?: string;
  generatedBy: string;
}

export async function generateIncidentExcel(data: IncidentExportData): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = data.companyName;
  workbook.created = new Date();
  
  const worksheet = workbook.addWorksheet('Incidents', {
    headerFooter: {
      firstHeader: `${data.companyName} - Incident Report`,
      firstFooter: `Generated by ${data.generatedBy} on ${new Date().toLocaleDateString('en-GB')}`
    }
  });

  // Define columns
  worksheet.columns = [
    { header: 'Reference', key: 'incidentRef', width: 20 },
    { header: 'Date', key: 'incidentDate', width: 15 },
    { header: 'Time', key: 'incidentTime', width: 10 },
    { header: 'Location', key: 'location', width: 20 },
    { header: 'Severity', key: 'severity', width: 12 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Person Type', key: 'personType', width: 15 },
    { header: 'Person Name', key: 'personName', width: 20 },
    { header: 'Staff Involved', key: 'staffInvolved', width: 20 },
    { header: 'Description', key: 'description', width: 40 },
    { header: 'Immediate Actions', key: 'immediateActions', width: 30 },
    { header: 'Witnesses', key: 'witnesses', width: 20 },
    { header: 'CQC Notified', key: 'notifiedCqc', width: 12 },
    { header: 'Council Notified', key: 'notifiedCouncil', width: 15 },
    { header: 'Police Notified', key: 'notifiedPolice', width: 14 },
    { header: 'Family Notified', key: 'notifiedFamily', width: 14 },
    { header: 'ICO Notified', key: 'notifiedIco', width: 12 },
    { header: 'Investigation Required', key: 'investigationRequired', width: 20 },
    { header: 'Investigation Notes', key: 'investigationNotes', width: 30 },
    { header: 'Actions Required', key: 'actionsRequired', width: 30 },
    { header: 'Lessons Learned', key: 'lessonsLearned', width: 30 },
    { header: 'Reported By', key: 'reportedBy', width: 20 },
    { header: 'Created', key: 'createdAt', width: 18 },
    { header: 'Last Updated', key: 'updatedAt', width: 18 },
  ];

  // Style header row
  const headerRow = worksheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF4F46E5' } // Indigo color
  };
  headerRow.alignment = { vertical: 'middle', horizontal: 'center' };
  headerRow.height = 25;

  // Add data rows
  data.incidents.forEach((incident) => {
    const row = worksheet.addRow({
      incidentRef: incident.incidentRef,
      incidentDate: incident.incidentDate ? new Date(incident.incidentDate).toLocaleDateString('en-GB') : '',
      incidentTime: incident.incidentTime || '',
      location: incident.location || '',
      severity: incident.severity || '',
      status: incident.status || '',
      personType: incident.personType || '',
      personName: incident.personName || '',
      staffInvolved: incident.staffInvolved || '',
      description: incident.description || '',
      immediateActions: incident.immediateActions || '',
      witnesses: incident.witnesses || '',
      notifiedCqc: incident.notifiedCqc ? 'Yes' : 'No',
      notifiedCouncil: incident.notifiedCouncil ? 'Yes' : 'No',
      notifiedPolice: incident.notifiedPolice ? 'Yes' : 'No',
      notifiedFamily: incident.notifiedFamily ? 'Yes' : 'No',
      notifiedIco: incident.notifiedIco ? 'Yes' : 'No',
      investigationRequired: incident.investigationRequired ? 'Yes' : 'No',
      investigationNotes: incident.investigationNotes || '',
      actionsRequired: incident.actionsRequired || '',
      lessonsLearned: incident.lessonsLearned || '',
      reportedBy: incident.reportedBy || '',
      createdAt: incident.createdAt ? new Date(incident.createdAt).toLocaleString('en-GB') : '',
      updatedAt: incident.updatedAt ? new Date(incident.updatedAt).toLocaleString('en-GB') : '',
    });

    // Apply severity-based coloring
    const severityCell = row.getCell('severity');
    if (incident.severity === 'critical') {
      severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEF4444' } };
      severityCell.font = { color: { argb: 'FFFFFFFF' } };
    } else if (incident.severity === 'high') {
      severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF97316' } };
      severityCell.font = { color: { argb: 'FFFFFFFF' } };
    } else if (incident.severity === 'medium') {
      severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEAB308' } };
    } else if (incident.severity === 'low') {
      severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF22C55E' } };
      severityCell.font = { color: { argb: 'FFFFFFFF' } };
    }

    // Apply status-based coloring
    const statusCell = row.getCell('status');
    if (incident.status === 'closed') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF22C55E' } };
      statusCell.font = { color: { argb: 'FFFFFFFF' } };
    } else if (incident.status === 'under_investigation') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF97316' } };
      statusCell.font = { color: { argb: 'FFFFFFFF' } };
    } else if (incident.status === 'open') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF3B82F6' } };
      statusCell.font = { color: { argb: 'FFFFFFFF' } };
    }

    // Wrap text for long content columns
    row.getCell('description').alignment = { wrapText: true };
    row.getCell('immediateActions').alignment = { wrapText: true };
    row.getCell('investigationNotes').alignment = { wrapText: true };
    row.getCell('actionsRequired').alignment = { wrapText: true };
    row.getCell('lessonsLearned').alignment = { wrapText: true };
  });

  // Add borders to all cells
  worksheet.eachRow((row, rowNumber) => {
    row.eachCell((cell) => {
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });
  });

  // Freeze header row
  worksheet.views = [{ state: 'frozen', ySplit: 1 }];

  // Add summary sheet
  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.columns = [
    { header: 'Metric', key: 'metric', width: 30 },
    { header: 'Value', key: 'value', width: 20 },
  ];

  // Style summary header
  const summaryHeader = summarySheet.getRow(1);
  summaryHeader.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  summaryHeader.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF4F46E5' }
  };

  // Calculate summary stats
  const totalIncidents = data.incidents.length;
  const openIncidents = data.incidents.filter(i => i.status === 'open').length;
  const closedIncidents = data.incidents.filter(i => i.status === 'closed').length;
  const underInvestigation = data.incidents.filter(i => i.status === 'under_investigation').length;
  const criticalIncidents = data.incidents.filter(i => i.severity === 'critical').length;
  const highIncidents = data.incidents.filter(i => i.severity === 'high').length;
  const mediumIncidents = data.incidents.filter(i => i.severity === 'medium').length;
  const lowIncidents = data.incidents.filter(i => i.severity === 'low').length;

  summarySheet.addRows([
    { metric: 'Total Incidents', value: totalIncidents },
    { metric: 'Open Incidents', value: openIncidents },
    { metric: 'Under Investigation', value: underInvestigation },
    { metric: 'Closed Incidents', value: closedIncidents },
    { metric: '', value: '' },
    { metric: 'Critical Severity', value: criticalIncidents },
    { metric: 'High Severity', value: highIncidents },
    { metric: 'Medium Severity', value: mediumIncidents },
    { metric: 'Low Severity', value: lowIncidents },
    { metric: '', value: '' },
    { metric: 'Report Generated', value: new Date().toLocaleString('en-GB') },
    { metric: 'Generated By', value: data.generatedBy },
    { metric: 'Company', value: data.companyName },
  ]);

  // Add borders to summary
  summarySheet.eachRow((row) => {
    row.eachCell((cell) => {
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });
  });

  // Generate buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
