import ExcelJS from 'exceljs';

interface IncidentData {
  id: number;
  incidentNumber: string | null;
  incidentDate: Date | string | null;
  incidentTime: string | null;
  locationId: number | null;
  severity: string | null;
  status: string | null;
  affectedPersonType: string | null;
  affectedPersonName: string | null;
  staffInvolved: string | null;
  description: string | null;
  immediateActions: string | null;
  witnessStatements: string | null;
  reportedToCqc: boolean | null;
  reportedToCouncil: boolean | null;
  reportedToPolice: boolean | null;
  familyNotified: boolean | null;
  reportedToIco: boolean | null;
  requiresInvestigation: boolean | null;
  investigationNotes: string | null;
  actionsRequired: string | null;
  lessonsLearned: string | null;
  reportedBy: string | null;
  createdAt: Date | string | null;
  updatedAt: Date | string | null;
  incidentType: string | null;
  locationDescription: string | null;
  serviceUserName: string | null;
}

interface IncidentExportData {
  incidents: IncidentData[];
  companyName: string;
  locationName?: string;
  generatedBy: string;
  locations?: { id: number; name: string }[];
}

// Helper to strip HTML tags
function stripHtml(html: string | null): string {
  if (!html) return '';
  return html.replace(/<[^>]*>/g, '').trim();
}

// Helper to format date
function formatDate(date: Date | string | null): string {
  if (!date) return '';
  const d = new Date(date);
  return d.toLocaleDateString('en-GB');
}

// Helper to format datetime
function formatDateTime(date: Date | string | null): string {
  if (!date) return '';
  const d = new Date(date);
  return d.toLocaleString('en-GB');
}

export async function generateIncidentExcel(data: IncidentExportData): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = data.companyName;
  workbook.created = new Date();
  
  const worksheet = workbook.addWorksheet('Incidents', {
    headerFooter: {
      firstHeader: `${data.companyName} - Incident Report`,
      firstFooter: `Generated by ${data.generatedBy} on ${new Date().toLocaleDateString('en-GB')}`
    }
  });

  // Define columns - matching actual database field names
  worksheet.columns = [
    { header: 'Reference', key: 'incidentNumber', width: 25 },
    { header: 'Date', key: 'incidentDate', width: 15 },
    { header: 'Time', key: 'incidentTime', width: 10 },
    { header: 'Type', key: 'incidentType', width: 20 },
    { header: 'Location', key: 'locationDescription', width: 25 },
    { header: 'Severity', key: 'severity', width: 12 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Person Type', key: 'affectedPersonType', width: 15 },
    { header: 'Person Name', key: 'affectedPersonName', width: 20 },
    { header: 'Staff Involved', key: 'staffInvolved', width: 25 },
    { header: 'Description', key: 'description', width: 50 },
    { header: 'Immediate Actions', key: 'immediateActions', width: 40 },
    { header: 'Witnesses', key: 'witnessStatements', width: 30 },
    { header: 'CQC Notified', key: 'reportedToCqc', width: 12 },
    { header: 'Council Notified', key: 'reportedToCouncil', width: 15 },
    { header: 'Police Notified', key: 'reportedToPolice', width: 14 },
    { header: 'Family Notified', key: 'familyNotified', width: 14 },
    { header: 'ICO Notified', key: 'reportedToIco', width: 12 },
    { header: 'Investigation Required', key: 'requiresInvestigation', width: 20 },
    { header: 'Investigation Notes', key: 'investigationNotes', width: 40 },
    { header: 'Actions Required', key: 'actionsRequired', width: 40 },
    { header: 'Lessons Learned', key: 'lessonsLearned', width: 40 },
    { header: 'Reported By', key: 'reportedBy', width: 20 },
    { header: 'Created', key: 'createdAt', width: 18 },
    { header: 'Last Updated', key: 'updatedAt', width: 18 },
  ];

  // Style header row
  const headerRow = worksheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF4F46E5' } // Indigo color
  };
  headerRow.alignment = { vertical: 'middle', horizontal: 'center' };
  headerRow.height = 25;

  // Add data rows - map database fields correctly
  data.incidents.forEach((incident) => {
    const row = worksheet.addRow({
      incidentNumber: incident.incidentNumber || '',
      incidentDate: formatDate(incident.incidentDate),
      incidentTime: incident.incidentTime || '',
      incidentType: incident.incidentType || '',
      locationDescription: incident.locationDescription || '',
      severity: incident.severity || '',
      status: incident.status || '',
      affectedPersonType: incident.affectedPersonType || '',
      affectedPersonName: incident.serviceUserName || incident.affectedPersonName || '',
      staffInvolved: stripHtml(incident.staffInvolved),
      description: stripHtml(incident.description),
      immediateActions: stripHtml(incident.immediateActions),
      witnessStatements: stripHtml(incident.witnessStatements),
      reportedToCqc: incident.reportedToCqc ? 'Yes' : 'No',
      reportedToCouncil: incident.reportedToCouncil ? 'Yes' : 'No',
      reportedToPolice: incident.reportedToPolice ? 'Yes' : 'No',
      familyNotified: incident.familyNotified ? 'Yes' : 'No',
      reportedToIco: incident.reportedToIco ? 'Yes' : 'No',
      requiresInvestigation: incident.requiresInvestigation ? 'Yes' : 'No',
      investigationNotes: stripHtml(incident.investigationNotes),
      actionsRequired: stripHtml(incident.actionsRequired),
      lessonsLearned: stripHtml(incident.lessonsLearned),
      reportedBy: incident.reportedBy || '',
      createdAt: formatDateTime(incident.createdAt),
      updatedAt: formatDateTime(incident.updatedAt),
    });

    // Apply severity-based coloring
    const severityCell = row.getCell('severity');
    if (incident.severity === 'critical') {
      severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEF4444' } };
      severityCell.font = { color: { argb: 'FFFFFFFF' } };
    } else if (incident.severity === 'high') {
      severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF97316' } };
      severityCell.font = { color: { argb: 'FFFFFFFF' } };
    } else if (incident.severity === 'medium') {
      severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEAB308' } };
    } else if (incident.severity === 'low') {
      severityCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF22C55E' } };
      severityCell.font = { color: { argb: 'FFFFFFFF' } };
    }

    // Apply status-based coloring
    const statusCell = row.getCell('status');
    if (incident.status === 'open') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDBEAFE' } };
    } else if (incident.status === 'under_investigation') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEF3C7' } };
    } else if (incident.status === 'closed') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD1FAE5' } };
    }

    // Wrap text for long content columns
    row.getCell('description').alignment = { wrapText: true, vertical: 'top' };
    row.getCell('immediateActions').alignment = { wrapText: true, vertical: 'top' };
    row.getCell('witnessStatements').alignment = { wrapText: true, vertical: 'top' };
    row.getCell('investigationNotes').alignment = { wrapText: true, vertical: 'top' };
    row.getCell('actionsRequired').alignment = { wrapText: true, vertical: 'top' };
    row.getCell('lessonsLearned').alignment = { wrapText: true, vertical: 'top' };
  });

  // Add summary sheet
  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.columns = [
    { header: 'Metric', key: 'metric', width: 25 },
    { header: 'Value', key: 'value', width: 30 },
  ];

  // Style summary header
  const summaryHeader = summarySheet.getRow(1);
  summaryHeader.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  summaryHeader.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF4F46E5' }
  };

  // Calculate summary stats
  const totalIncidents = data.incidents.length;
  const openIncidents = data.incidents.filter(i => i.status === 'open').length;
  const underInvestigation = data.incidents.filter(i => i.status === 'under_investigation').length;
  const closedIncidents = data.incidents.filter(i => i.status === 'closed').length;
  const criticalSeverity = data.incidents.filter(i => i.severity === 'critical').length;
  const highSeverity = data.incidents.filter(i => i.severity === 'high').length;
  const mediumSeverity = data.incidents.filter(i => i.severity === 'medium').length;
  const lowSeverity = data.incidents.filter(i => i.severity === 'low').length;

  // Add summary data
  summarySheet.addRow({ metric: 'Total Incidents', value: totalIncidents });
  summarySheet.addRow({ metric: 'Open Incidents', value: openIncidents });
  summarySheet.addRow({ metric: 'Under Investigation', value: underInvestigation });
  summarySheet.addRow({ metric: 'Closed Incidents', value: closedIncidents });
  summarySheet.addRow({ metric: '', value: '' });
  summarySheet.addRow({ metric: 'Critical Severity', value: criticalSeverity });
  summarySheet.addRow({ metric: 'High Severity', value: highSeverity });
  summarySheet.addRow({ metric: 'Medium Severity', value: mediumSeverity });
  summarySheet.addRow({ metric: 'Low Severity', value: lowSeverity });
  summarySheet.addRow({ metric: '', value: '' });
  summarySheet.addRow({ metric: 'Report Generated', value: formatDateTime(new Date()) });
  summarySheet.addRow({ metric: 'Generated By', value: data.generatedBy });
  summarySheet.addRow({ metric: 'Company', value: data.companyName });
  if (data.locationName) {
    summarySheet.addRow({ metric: 'Location Filter', value: data.locationName });
  }

  // Generate buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
